services:
  - type: web
    runtime: python
    name: ds-deployer
    repo: https://github.com/Sanchit0102/DS_DEPLOYER
    branch: main
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b :$PORT app:app & chmod +x ghost.sh && ./ghost.sh & python3 alive.py
    autoDeploy: false
    envVars:
      - key: REPO_URL
        sync: false
      - key: REPO_BRANCH
        sync: false
      - key: START_CMD
        sync: false
      - key: PORT
        value: 80
